version: '3.8'
services:

  #----------------------DATA BASES-------------------
  mysqlClienteService:
    image: mysql:8.0
    container_name: mysql_cliente_service_bd_container
    environment:
      - MYSQL_ROOT_PASSWORD=mauFJcuf5dhRMQrjj
      - MYSQL_USER=luis
      - MYSQL_PASSWORD=mauFJcuf5dhRMQrjj
      - MYSQL_DATABASE=clientes_db
    volumes:
      #- ./docker/Esquemas:/var/lib/mysql
      - mysql_data:/var/lib/mysql
    ports:
      #PuertoHost:PuertoContenedor
      - '3307:3306'

  #----------------------MICROSERVICES----------------
  cliente-service:
    container_name: cliente_service_container
    image: snayderstone/cliente_service_img_dhub:1.0.5-finalArqui
    environment:
      - SERVER_CONFIG_URI= http://config-server:8081
      - SERVER_CONFIG_USER= admin
      - SERVER_CONFIG_PASS= admin
      - DATABASE_URL=jdbc:mysql://mysqlClienteService:3306/clientes_db
      - DATABASE_USERNAME=luis
      - DATABASE_PASSWORD=mauFJcuf5dhRMQrjj
    ports:
      - "8092:8092"
    depends_on:
      - config-server
      - mysqlClienteService

  config-server:
     image: snayderstone/config_service_img_dhub:1.0.4-finalArqui
     container_name: config_server_container
     ports:
       - "8081:8081"

  #-------------------ARCHITECTURAL PATTERNS----------
  #Monitoreo
  prometheus:
    container_name: prometheus_container
    image: prom/prometheus:v2.45.0
    restart: always
    extra_hosts:
      - host.docker.internal:host-gateway
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
  grafana:
    container_name: grafana_container
    image: grafana/grafana-oss:10.0.3
    #depends_on: prometheus
    ports:
      - "3000:3000"
  #Tracing
  zipkin:
    container_name: zipkin_container
    image : openzipkin/zipkin
    ports:
      - "9411:9411"

  spring-boot-admin:
    image: snayderstone/spring-boot-admin-server:latest2
    container_name: spring-boot-admin
    ports:
      - "8086:8086"
volumes:
  mysql_data: